from translater import get_text as _

LOCATIONS = {
    'Mercury': _('Mercury'),
    'Venus': _('Venus'),
    'Fortune': _('Fortune'),
    'Earth': _('Earth'),
    'Cetus': _('Cetus'),
    'Mars': _('Mars'),
    'Phobos': _('Phobos'),
    'Deimos': _('Deimos'),
    'Cambion Drift': _('Cambion Drift'),
    'Ceres': _('Ceres'),
    'Jupiter': _('Jupiter'),
    'Europa': _('Europa'),
    'Saturn': _('Saturn'),
    'Uranus': _('Uranus'),
    'Neptune': _('Neptune'),
    'Pluto': _('Pluto'),
    'Sedna': _('Sedna'),
    'Eris': _('Eris'),
    'Void': _('Void'),
    'Lua': _('Lua'),
    'Kuva Fortress': _('Kuva Fortress'),
    'Zariman': _('Zariman'),
    'Earth Proxima': _('Earth Proxima'),
    'Venus Proxima': _('Venus Proxima'),
    'Saturn Proxima': _('Saturn Proxima'),
    'Neptune Proxima': _('Neptune Proxima'),
    'Pluto Proxima': _('Pluto Proxima'),
    'Veil Proxima': _('Veil Proxima'),
}
ENEMIES = {
    'Corpus': _('Corpus'),
    'Grineer': _('Grineer'),
    'Orokin': _('Orokin'),
    'Infested': _('Infested'),
    'Crossfire': _('Crossfire'),
}
TYPES = {
    'Assault': _('Assault'),
    'Capture': _('Capture'),
    'Defense': _('Defense'),
    'Disruption': _('Disruption'),
    'Excavation': _('Excavation'),
    'Extermination': _('Extermination'),
    'Interception': _('Interception'),
    'Mobile Defense': _('Mobile Defense'),
    'Rescue': _('Rescue'),
    'Sabotage': _('Sabotage'),
    'Skirmish': _('Skirmish'),
    'Spy': _('Spy'),
    'Survival': _('Survival'),
    'Volatile': _('Volatile'),
    'Orphix': _('Orphix'),
    'Hive': _('Hive'),
}
TIERS = {
    'Lith': _('Lith'),
    'Meso': _('Meso'),
    'Neo': _('Neo'),
    'Axi': _('Axi'),
    'Requiem': _('Requiem'),
}
CYCLES = {
    'day': _('Day'),
    'night': _('Nigth'),
    'cold': _('Nigth'),
    'warm': _('Nigth'),
    'vome': _('Vome'),
    'fass': _('Fass'),
    'corpus': _('Corpus'),
    'grineer': _('Grineer'),
}
